name: 'Composite Action - Get & Cache Dependencies'
description: 'This is a demo for composite action type'
inputs:
  caching:
    description: 'Turn caching on/off (default: true)'
    required: false
    default: 'true'
  run-path:
    description: 'On which working-directory the run commands will apply'
    required: false
    default: '.'
outputs:
  used-cache:
    description: 'Output if cache was used or not'
    value: ${{ steps.install.outputs.cache }}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v4
      with:
        path: custom-actions/node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      id: install
      shell: bash
      working-directory: ${{ inputs.run-path }}
      run: |
        npm ci
        echo "cache='${{ inputs.caching }}'" >> $GITHUB_OUTPUT
      