name: Test basic-website
on: [push, workflow_dispatch]
jobs:
    test:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: basic-website
      steps:
        - name: Get code
          # Specify the used action
          # Download repository
          uses: actions/checkout@v4
          # Options for mentioned action
          # with:
        - name: Install NodeJS
          uses: actions/setup-node@v4
          with:
            node-version: 18
        - name: Install dependencies
          run: npm ci
        - name: Run tests
          run: npm test
    lint:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: basic-website
      steps:
        - name: Get code
          uses: actions/checkout@v4
        - name: Install NodeJS
          uses: actions/setup-node@v4
          with:
            node-version: 18
        - name: Install dependencies
          run: npm ci
        - name: Lint
          run: npm run lint
    deploy:
      # Waits for mentioned jobs to finish succesfully before running
      needs: [test, lint]
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: basic-website
      steps:
        - name: Get code
          uses: actions/checkout@v4
        - name: Install NodeJS
          uses: actions/setup-node@v4
          with:
            node-version: 18
        - name: Install dependencies
          run: npm ci
        - name: Build project
          run: npm run build
        - name: Deploy
          run: echo "Deploying..."
