# Name of workflow
name: Basic Workflow
# When the workflow is triggered
# workflow_dispatch - manual triggered
on: workflow_dispatch

jobs:
  # Job name
  first-job:
    # Environment on what the job runs
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners
    runs-on: ubuntu-latest
    # Like tasks in Ansible; simple commands
    steps:
      # Name of the step
      - name: Print greeting
        # An action (like module)
        # Run: shell command
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Goodbye!"
