name: Custom Actions
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: custom-actions
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Load & cache dependencies
        # If there is another repository specialized only for actions it could be used like this
        # uses: M13X/my-action
        # Since this is a local defined action it is used like this:
        uses: ./.github/actions/cached-deps
      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: custom-actions
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Load & cache dependencies
        # If there is another repository specialized only for actions it could be used like this
        # uses: M13X/my-action
        # Since this is a local defined action it is used like this:
        uses: ./.github/actions/cached-deps
      - name: Test code
        id: run-tests
        run: npm run test
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: custom-actions/test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: custom-actions
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: custom-actions/node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build website
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: custom-actions/dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: custom-actions
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: custom-actions/dist
      - name: Output contents
        run: ls
      - name: Deploy site
        run: echo "Deploying..."