# https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
name: Eviropnment variables
on:
  push:
    branches:
      - main
      - dev
env:
  MONGODB_DB_NAME: database_demo
jobs:
  test:
    env:
      MONGODB_CLUSTER_ADDRESS: learning-cluster.aecfiri.mongodb.net
      # Can add important information as secrets by configuring repository
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      PORT: 8080
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: node-app
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Run tests
        run: npm test
      - name: Output information
        # To access an environment variable any of these methods
        run: | 
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"
          echo "MONGO_DB_NAME: $MONGODB_DB_NAME"
        # The last one is shell based, therefore it will not work on Windows
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |        
          echo "..."
